image:
  tag: "10.0.9"
grafana.ini:
  feature_toggles:
    nestedFolders: true
extraContainers: |
  - name: git-sync
    image: registry.k8s.io/git-sync/git-sync:v4.1.0
    args:
    - --repo=https://github.com/locmai/grafana-dashboards
    - --root=/var/lib/grafana/dashboards
    - --link=next-gen
    - --period=30s
    volumeMounts:
    - name: next-gen 
      mountPath: /var/lib/grafana/dashboards
extraEmptyDirMounts:
  - name: next-gen
    mountPath: /var/lib/grafana/dashboards
    readOnly: true
dashboardProviders:
 dashboardproviders.yaml:
   apiVersion: 1
   providers:
   - name: next-gen
     orgId: 1
     folder: 'Next-generation'
     folderUid: 'next-gen'
     type: file
     disabledDeletion: true
     allowUiUpdates: false
     editable: false
     options:
        path: /var/lib/grafana/dashboards/next-gen
